#!/bin/sh

NUMBER_OF_SCREENS="$(xrandr | grep -c '\*')"

if [ "$NUMBER_OF_SCREENS" -gt 1 ]
then
    maim ~/.cache/lock.png
    corrupter ~/.cache/lock.png ~/.cache/lock.png
fi

i3lock -e -b -f -i ~/.cache/lock.png
